// this file is @generated by Perseid; edit the shared runtime template.
package com.meteroid.exceptions;

/**
 * Base of every exception the SDK throws: {@link ApiException} for error responses, {@link
 * ApiConnectionException} and {@link ApiTimeoutException} when no response came, and {@link
 * InvalidDataException} when a response is not what the API describes.
 */
public class MeteroidException extends RuntimeException {
    private static final long serialVersionUID = 1L;

    /**
     * An exception with a message.
     *
     * @param message what went wrong
     */
    public MeteroidException(String message) {
        super(message);
    }

    /**
     * An exception with a message and a cause.
     *
     * @param message what went wrong
     * @param cause the exception that caused it
     */
    public MeteroidException(String message, Throwable cause) {
        super(message, cause);
    }
}
